name: Deploy to van-view-tempalte/doc

on:
  push:
    branches:
      - main  # 触发条件可以根据你的实际情况修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Deploy to van-view-tempalte/doc
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd docs/.vitepress/dist
          git init
          git remote add destination https://github.com/van-view-tempalte/doc.git
          git add .
          git commit -m "Deploy"
          git push -f destination master
